server:
  port: 8081

web_sockets:
  lobby_pattern: "/topic/lobby/"
  user_pattern: "/topic/client/"
  connection_checker_delay-s: 1

security:
  jwt:
    secret: "vergetghetwbhtrhhwryhryhnrw54h46hnyfgnfgnytn"
