package ru.rsreu.jackal.websocket.dto

enum class WebSocketResponseType {
    CONNECTED_INFO_FOR_ALL, CONNECTED_INFO_FOR_ONE, CONNECTION_ERROR, LEAVED_INFO_FOR_ALL, LEAVED_INFO_FOR_ONE, LEAVING_ERROR
}